
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2db
spec:
  selector:
    matchLabels:
      app: h2db
  template:
    metadata:
      labels:
        app: h2db
    spec:
      containers:
      - name: h2db
        image: joedoe/h2db
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 81
          name: web
        - containerPort: 1521
          name: jdbc
        volumeMounts:
        - name: h2db-storage
          mountPath: /data
      volumes:
        - name: h2db-storage
          persistentVolumeClaim:
            claimName: h2db-volume-claim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h2db-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: h2db-service
spec:
  type: LoadBalancer
  selector:
    app: h2db
  ports:
  - port: 81
    targetPort: 81
    name: web
  - port: 1521
    targetPort: 1521
    name: jdbc

