apiVersion: v1
kind: ConfigMap
metadata:
  name: counter-config
  labels:
    app: counter-config
data:
  application.properties: |
    server.port=8081
    spring.datasource.url=jdbc:h2:tcp://h2db-service:1521/~/counterdb
    spring.datasource.driverClassName=org.h2.Driver
    spring.datasource.username=sa
    spring.datasource.password=
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto=update