
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deployment
  labels:
    app: counter-deployment
spec:
  selector:
    matchLabels:
      app: counter-deployment
  template:
    metadata:
      labels:
        app: counter-deployment
    spec:
      containers:
      - name: counter-deployment
        image: roliiii/counter:${project.version}
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: counter-config


