apiVersion: v1
kind: Service
metadata:
  name: counter-service
  labels:
    app: counter-service
spec:
  type: LoadBalancer
  selector:
    app: counter-deployment
  ports:
    - port: 8081
      targetPort: 8081